# Site Settings
lang: en
# title: Bulma Clean Theme
# tagline: Bulma Clean Theme
email: kithminrw@gmail.com
description: >
  Kithmin's Personal Blog
baseurl: ""
url: "https://www.kithminrw.com"
image_dir: "/img"
permalink: pretty
favicon: ./favicon.png
theme_color: '#02343F'
fixed_navbar: top
timezone: America/Los_Angeles
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: dark

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: kithminrw


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Kithmin Randula"
      layout: post
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    show_sidebar: false
